MKFirmware/MK4duo

MK4duo/src/eeprom/eeprom.cpp
MK4duo/src/macros.h

Fixed an issue in eeprom.cpp while compiling with EEPROM enabled and HAS_BED_LEVELING==false

Fixed eeprom.cpp, and STRINGIFY macro

---

MK4duo/src/MK_Main.cpp
MK4duo/src/endstop/endstops.cpp
MK4duo/src/mechanics/cartesian_mechanics.cpp
MK4duo/src/mechanics/core_mechanics.cpp
MK4duo/src/mechanics/mechanics.h
MK4duo/src/stepper/stepper.cpp
MK4duo/src/stepper/stepper_indirection.h

Fix issue n° #133 . I'm not sure if it's ok but now it compiles without errors.
Some variables where used with different names. I'm not sure if that was intentional or not, but the ones with "extruder" instead of "hotend" were not declared anywhere in MK4duo.
I have:
- fixed some "mechanics.VARIABLE" problems due to "mechanics." missing
- replaced **active_extruder_parked** with **active_hotend_parked** (as defined in cartesian_mechanics.h line 54)
- replaced **inactive_extruder_x_pos** with **inactive_hotend_x_pos** (as defined in cartesian_mechanics.h line 49)
- replaced **duplicate_extruder_x_offset** with **duplicate_hotend_x_offset** (as defined in cartesian_mechanics.h line 51)
- replaced **#if ENABLED(WORKSPACE_OFFSETS)** with **#if ENABLED(WORKSPACE_OFFSETS) || …

Fix bug in DUAL_X_CARRIAGE

---

MK4duo/base.h
MK4duo/src/gcode/motion/g0_g1.h
MK4duo/src/gcode/multimode/g7.h
MK4duo/src/gcode/scara/m360_m364.h
MK4duo/src/macros.h
MK4duo/src/mechanics/cartesian_mechanics.cpp
MK4duo/src/mechanics/cartesian_mechanics.h
MK4duo/src/mechanics/core_mechanics.cpp
MK4duo/src/mechanics/core_mechanics.h
MK4duo/src/mechanics/delta_mechanics.cpp
MK4duo/src/mechanics/delta_mechanics.h
MK4duo/src/mechanics/mechanics.cpp
MK4duo/src/mechanics/mechanics.h
MK4duo/src/mechanics/scara_mechanics.cpp
MK4duo/src/mechanics/scara_mechanics.h

Buon ferragosto, Mago :)
Added **initial** support for SCARA mechanics. I've added only some of the SCARA specific functions, **more are missing**.
Fixed and cleared some gcode functions (g0_g1, g7, m360_m364).
Since every `prepare_move_to_destination()` started in the same way, I've created a `prepare_move_to_destination()` in `Mechanics` with the code common to every mechanics. When the mechanics specific code needs to be executed, `prepare_move_to_destination_mech_specific()` is called. That is a pure virtual function of `Mechanics`: is virtual but is not implemented in `Mechanics` (and so it doesn't need to be `override`). This way `Mechanics` automatically becomes an abstract class (**as it should be**): this forces the compiler to check that a `Mechanics` object is NEVER created. …

Initial support for SCARA (and more)

---

MK4duo/src/boards/1401.h
MK4duo/src/boards/1433.h
MK4duo/src/boards/33.h
MK4duo/src/gcode/sensor/m404_m407.h
contributing.md
issue_template.md

Ramps4Due it's a modified Ramps board. In Marlin, display pins are the same used for the Ramps.
Added display pins to 1433.h and little fix (BEEPER_PIN -> ORIG_BEEPER_PIN) in 33.h to fix #127 and #199 still open issues.
Updated contribution.md and issue_template.md to prevent sanitycheck.h errors to be reported in the issues...
Little fixes in Radds board (1401.h)
Updated M406 code according to the latest change in Marlin bugfix-1.1.x

Displays for Ramps4Due

---

MK4duo/src/HAL/HAL_AVR/HardwareSerial.cpp
MK4duo/src/commands/commands.cpp
MK4duo/src/commands/parser.cpp
MK4duo/src/commands/parser.h
MK4duo/src/eeprom/eeprom.cpp
MK4duo/src/endstop/endstops.cpp
MK4duo/src/gcode/calibrate/g29_mbl.h
MK4duo/src/gcode/control/m42.h
MK4duo/src/gcode/debug/m43.h
MK4duo/src/gcode/mixing/m163_m165.h
MK4duo/src/gcode/tools/tcode.h
MK4duo/src/lcd/ultralcd_impl_HD44780.h
MK4duo/src/pins.h
MK4duo/src/printer/printer.cpp
MK4duo/src/printer/printer.h
MK4duo/src/utility/pinsdebug.h

Fix warnings and errors both from #199 and from #204.
Added full COLOR_MIXING_EXTRUDER support, implementing get_mix_from_command() and store_normalized_mixing_factors().
Old behavior of mixing factors is preserved (you can still insert values which add up to 1.0) but it's now possible to insert values as you want (like 10, 37, 85, 0 , 2). They will be normalized before being stored.

Fix warnings, errors and COLOR_MIXING_EXTRUDER full support

---

MK4duo/src/conditionals_pre.h
MK4duo/src/gcode/config/m301.h
MK4duo/src/gcode/config/m305.h
MK4duo/src/lcd/ultralcd.cpp
MK4duo/src/temperature/temperature.cpp

Really small fixes to PIDTEMP macro. In conditionals_pre.h, if the machine has no extruders (maybe because it is used as laser cutting or cncrouter), PIDTEMP must be defined as false, actually PIDTEMP must be always defined! @MagoKimbra , should we put some new sanitycheck controls to check if PIDTEMP, PIDTEMPBED, ... , PWM_HARDWARE, ... and macros like those are defined?

PIDTEMP small fixes

---

MK4duo/src/gcode/config/m200.h
MK4duo/src/gcode/config/m221.h
MK4duo/src/gcode/config/m222.h
MK4duo/src/gcode/config/m906.h
MK4duo/src/gcode/sensor/m602_m604.h
MK4duo/src/gcode/temperature/m104.h
MK4duo/src/gcode/temperature/m109.h

Note: in m906.h, I deleted a CODE_M906 macro because it was already defined at the beginning of the file, so it was useless

Fix for #199

---

MK4duo/src/boards/1401.h
MK4duo/src/gcode/calibrate/g29_abl.h
MK4duo/src/gcode/temperature/m191.h
MK4duo/src/gcode/temperature/m192.h
MK4duo/src/sanitycheck.h
MK4duo/src/sd/SDFat.cpp
MK4duo/src/sd/cardreader.cpp

Ciao Alberto,
c'è un warning che mi preoccupa un po' ma su cui non saprei intervenire, dice che in Temperature.cpp viene superato il limite superiore di un array, causando la lettura di dati che non appartengono a quell'array ma che sono localizzati in un'area di memoria immediatamente adiacente. Il che porta a leggere "valori spazzatura". Magari non c'è nessun problema, però ti consiglio di darci un'occhiata:
```
sketch/src/temperature/temperature.cpp: In static member function 'static void Temperature::set_current_temp_raw()':
sketch/src/temperature/temperature.cpp:288:78: warning: array subscript is above array bounds [-Warray-bounds]
LOOP_HEATER() heaters[h].current_temperature_raw = HAL::AnalogInputValues[h];
^
```
HAL::AnalogInputValues ha dimensione ANALOG_INPUTS, non so in che …

Fix #222 and some warnings

---

Documentation/Features.md
MK4duo/Configuration_Delta.h
MK4duo/plugin Repetier/marlineeprom.xml
MK4duo/src/eeprom/eeprom.cpp
MK4duo/src/gcode/delta/m666.h
MK4duo/src/lcd/ultralcd.cpp
MK4duo/src/mechanics/delta_mechanics.cpp
MK4duo/src/mechanics/delta_mechanics.h
MK4duo/src/sanitycheck.h

renamed defines and variables to have polar representation names and not from cartesian (position), which is confusing for user:
TOWER_X_RADIUS_ADJ  ->  TOWER_X_ANGLE_ADJ
TOWER_X_POSITION_ADJ  ->  TOWER_X_RADIUS_ADJ
where X stands for A, B and C tower
delta_tower_radius_adj  ->  delta_tower_angle_adj
delta_tower_pos_adj  ->  delta_tower_radius_adj
also updated serial output, comments and doc

delta: renamed defines and vars to make more meaning for tower adjustment (polar: radius and angle)

---

MK4duo/src/commands/parser.cpp
MK4duo/src/gcode/calibrate/g42.h
MK4duo/src/gcode/gcode.h
MK4duo/src/gcode/geometry/m206.h
MK4duo/src/gcode/motion/g2_g3.h
MK4duo/src/gcode/scara/m665.h
MK4duo/src/mechanics/cartesian_mechanics.h
MK4duo/src/mechanics/core_mechanics.h
MK4duo/src/mechanics/delta_mechanics.h
MK4duo/src/mechanics/mechanics.cpp
MK4duo/src/mechanics/mechanics.h
MK4duo/src/mechanics/scara_mechanics.cpp
MK4duo/src/mechanics/scara_mechanics.h
MK4duo/src/planner/planner.h
MK4duo/src/stepper/stepper.cpp
MK4duo/src/stepper/stepper.h

Compilando per MORGAN_SCARA o MAKERARM_SCARA dà ancora alcuni errori: uno dovuto alla mancanza delle funzioni Transform e Home in scara_mechanics e un altro legato alla macro MACHINE_TYPE. Per il resto, ho confrontato le funzioni di Marlin 1.1.5 con MK4duo. E' probabile che abbia copiato qualcosa di Marlin che non va bene per MK4duo, quando hai tempo dacci un'occhiata.
C'è una funzione che ho dichiarato così:
`virtual void homeaxis(const AxisEnum axis) = 0;`
Quel " = 0;" è voluto, non è un errore: significa che la funzione è virtuale pura, ovvero in mechanics.cpp non appare l'implementazione di homeaxis e quindi le classi figlie sono costrette ad implementarla, pena un errore di compilazione.

Supporto completo (o quasi) a SCARA

---

MK4duo/src/HAL/I2cEeprom.cpp
MK4duo/src/HAL/SpiEeprom.cpp

I2C_EEPROM and SPI_EEPROM code loading is needed only if EEPROM_SETTINGS is enabled.

Fix I2C and SPI eeprom

---

MK4duo/src/lcd/nextion/Nextion_lcd.cpp

Add 2.4" and 2.8" Nextion display support for 3D GFX Preview to work with [Firmware for Nextion 2.4" or 2.8"](https://github.com/iworld4us/nextion-2.4).

Add 2.4" and 2.8" support for 3D GFX Preview

---

MK4duo/src/boards/1404.h

This PR is related to #385 and #369 . It turned out that the needed pin definitions were identical to those found in 33.h (RAMPS 1.4)

Added MKS 12864 OLED support to Ramps FD v2

---

MK4duo/Configuration_Feature.h
MK4duo/src/core/commands/gcode/control/m540.h
MK4duo/src/core/endstop/endstops.cpp
MK4duo/src/core/endstop/sanitycheck.h
MK4duo/src/core/stepper/stepper.cpp
MK4duo/src/core/stepper/stepper.h
MK4duo/src/lcd/ultralcd.cpp
MK4duo/src/sd/cardreader.cpp

@MagoKimbra is this ok? I wanted to have ABORT_ON_ENDSTOP_HIT in my printer even without having SDSUPPORT, just as a safety measure. The main changes are in endstop.cpp

Clean and fix ABORT_ON_ENDSTOP_HIT

---

MK4duo/src/boards/70.h
MK4duo/src/boards/701.h
MK4duo/src/boards/702.h
MK4duo/src/boards/703.h

This is the continuation of PR #505.
Replacing `NoPin` macro with "-1" inside board files caused the replacement of some "-1" which didn't refer to pins but to temperature sensor types. This can create some confusion.

Fix 70.h, 701.h, 702.h, 703.h

---

MK4duo/src/HAL/I2cEeprom.cpp
MK4duo/src/boards/1705.h

A much cleaner version of #549 as suggested by @silversat and @remspoor in #258.
Ultratronics board has I2C connectors linked to the second I2C port of the SAM3X8E chip. This changes handle this particular case.

Ultratronics EEPROM uses I2C port 1

---

MK4duo/src/core/commands/gcode/temperature/m192.h
MK4duo/src/core/temperature/sanitycheck.h

Hi @MagoKimbra. This fixes #652. **_I've already fixed this for `4_3_7` branch with the same changes._** Now we need to add these changes also to `master` and then to `4_3_8`.
It's a very simple fix... in `m192.h` there's a variable with the wrong name.
The error was introduced in `4_3_7` version

Fix #652 also for 4_3_8 version

---

MK4duo/src/language/language_en.h
MK4duo/src/language/language_it.h
MK4duo/src/lcd/menu/menu_main.cpp

I figured out that the TMC2130 diag1 pin is in opendrain "mode". I use a DUE "ultratonics" board. The internal pullup is not strong enough against the opendrain from the TMC2130. Even with inverted Endstops and pullups, Sensorless homing is not working because the max Voltage is about 1.3V. So I would like to have a switch so choose between diag1 as pushpull or open drain output. I guess the most users would like to have the pushpull diag1 except the  EinsyRambo users. Here is a good discussion on the Marlin fork https://github.com/MarlinFirmware/Marlin/issues/10294
( this is my first request, sorry if I did a mistake, please advise me)

TMC2130 diag1 pushpull/open

---

MK4duo/src/feature/bedlevel/ubl/ubl_g29.cpp

Can't compile with unclosed string.

Unclosed quotation mark fix.

---

MK4duo/src/boards/2706.h
MK4duo/src/platform/HAL_SAMD/HAL.cpp

1. Corrected the order of the heater pins as described in https://reprapworld.com/datasheets/datasheet_minitronics_20_20181003.pdf
2. Changed endstopps fo me MIN instead of MAX.
3. Using ADCAveragingFilter for the temperature in SAMD's HAL.

Fixes for Minitronics V2
