MK4duo/src/motion/stepper.cpp
small fix for correct compile CORE* firmware
=> syntax fix

MK4duo/Configuration_Basic.h, MK4duo/Configuration_Delta.h, MK4duo/Configuration_Feature.h, MK4duo/Configuration_Temperature.h, MK4duo/src/boards/408.h
changed the smart ramps configuration file (408.h)
=> MAX6675 or MAX31855 support on Smart Ramps board

MK4duo/src/boards/41.h
=> Fix MKS Mini Board (41)

MK4duo/src/boards/67.h
Tested, work fine.
But need non-standart pins adapter
=> pinout for AzteegX3 + Reprapworld Graphical LCD

MK4duo/Boards.h, MK4duo/src/boards/77.h, MK4duo/src/boards/78.h, MK4duo/src/boards/79.h
Velleman K8400 (3DVERTEX) board support
=> Added 79.h file (3DVERTEX board support)

MK4duo/src/MK_Main.cpp, MK4duo/src/laser/laser.h, MK4duo/src/laser/laser_avr.cpp, MK4duo/src/laser/laser_sam.cpp, MK4duo/src/lcd/buzzer.cpp, MK4duo/src/lcd/buzzer.h, MK4duo/src/lcd/ultralcd.cpp, MK4duo/src/lcd/ultralcd_impl_DOGM.h, MK4duo/src/sanitycheck.h, MK4duo/src/stepper/stepper.cpp, MK4duo/src/temperature/temperature.cpp
Two functions in laser class have a problem. Please check them after merging the pull request!
- void update_lifetime() : it's never implemented nor used in MK4duo
- void diagnose() : it's implemented in laser_sam.cpp but not in laser_avr.cpp . However, it's not used anywhere in MK4duo
=> Laser and Buzzer classes created!

MK4duo/src/laser/laser.h, MK4duo/src/laser/laser_avr.cpp
I tried to simplify and optimize laser_avr.
Code compiles.
**This doesn't modify the behaviour of the code**
=> Tried to simplify laser_avr for future development

.gitattributes
This PR makes github recognize this project as an Arduino project! 😃
=> Override the language heuristics

MK4duo/src/cncrouter/cncrouter.cpp, MK4duo/src/gcode/multimode/g7.h, MK4duo/src/mechanics/mechanics.cpp
Clear code in mechanics.cpp
Fixed typo in g7.h
Clear code in cncrouter.cpp (which has still to be transformed into a class)
=> Clear code

MK4duo/src/lcd/ultralcd.cpp
Looks like you forgot about this part during a recent refactor 🙂
=> Fix ultralcd.cpp LEVEL_BED_CORNERS procedure

MK4duo/src/boards/1403.h, MK4duo/src/gcode/control/m355.h, MK4duo/src/gcode/debug/m43.h, MK4duo/src/heater/heater.cpp, MK4duo/src/heater/heater.h, MK4duo/src/laser/laser_avr.cpp, MK4duo/src/laser/laser_sam.cpp, MK4duo/src/lcd/ultralcd.cpp, MK4duo/src/printer/printer.cpp, MK4duo/src/sensor/flowmeter.cpp, MK4duo/src/servo/servo.cpp, MK4duo/src/temperature/temperature.h, MK4duo/src/utility/pinsdebug.h
=> Fix and clear code

MK4duo/src/feature/laser/laser.h, MK4duo/src/planner/planner.cpp, MK4duo/src/stepper/stepper.cpp
After extensive testing I found out that the fix #302 was not quite correct. At high speeds, communication collapsed and only a few commands were executed.
With this change, it works now.
=> Fix Laser Raster / Laser Pulsed for Arduino Due

MK4duo/src/boards/65.h
Scusami Mago, stavo caricando questa minuscola modifica nella pull request ma sei stato più veloce tu :-)
=> Fix missing #endif

MK4duo/Boards.h, MK4duo/src/boards/302.h, MK4duo/src/boards/303.h
Added MiniRambo 1.0a and MiniRambo (they have some little differences)
=> Add MiniRambo boards

MK4duo/Boards.h, MK4duo/src/boards/1407.h
Add support for `ULTIMAKER4DUE` board to use with [iworld4us.com/diy-3d-printer.html](https://iworld4us.com/diy-3d-printer.html).
```
Ultimaker Shield + Arduino DUE Aleksandr Varaksa mods
```
=> Add support for ULTIMAKER4DUE board

MK4duo/src/core/eeprom/eeprom.cpp, MK4duo/src/core/temperature/sanitycheck.h
Hi @MagoKimbra. I'm currently working on the RepetierHost XML for eeprom definitions. With this PR I added some output that was missing in M503 command. I also cleaned it a bit.
* Added M305 and M306 output also for CHAMBER and COOLER
* Added M305 D0 P S output (for DHT_SENSOR)
* Added M208 R parameter output
* Cleaned for loops in M503 code
* Added sanity check for DHT sensor
=> Fix M503 output

MK4duo/plugin Repetier/marlineeprom.xml
Il plugin di Repetier non supporta il tipo "bool", l'ho riportato al tipo "int"
=> Fix marlineeprom.xml

MK4duo/src/core/mechanics/scara_mechanics.cpp
=> Fix Z homing with SCARA

MK4duo/src/boards/2706.h, MK4duo/src/platform/HAL_DUE/HAL.h, MK4duo/src/platform/HAL_SAMD/HAL.cpp, MK4duo/src/platform/HAL_SAMD/HAL.h, MK4duo/src/platform/HAL_SAMD/math.h, MK4duo/src/sd/SDFat.cpp, MK4duo/src/sd/SDFat.h
=>  Fix typos, compilation problems

MK4duo/plugin Repetier/marlineeprom.xml, MK4duo/src/core/eeprom/eeprom.cpp, MK4duo/src/core/endstop/endstops.cpp, MK4duo/src/core/endstop/endstops.h
Added complete endstop settings management
Now file `marlineeprom.xml` is compatible also with Repetier Server
=> Complete support to EEPROM

MK4duo/src/lcd/nextion/library/Nextion.cpp
- Added more debug to Nextion library
- Added a 100ms wait, so serial can send out the baud command before terminating the connection
=> Nextion improvements

MK4duo/src/core/commands/gcode/temperature/m192.h, MK4duo/src/core/temperature/sanitycheck.h
ATTENTION: this fixes will be applied to 4_3_7 only. They are needed also in 4_3_8 !!!
=> Fix #652 m192 no_wait_for_cooling
